# API Gateway application properties

spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            httpclient:
                connect-timeout: 50000
                response-timeout: 50s
            default-filters:
                - name:
                    args:
                        retries: 3
                        methods: GET,POST,PUT,DELETE
                        statuses: BAD_GATEWAY
                        backoff:
                            firstBackoff: 10ms
                            maxBackoff: 50ms
                            factor: 2
                            basedOnPreviousValue: false
